/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAdvogadosRouteImport } from './routes/_authenticated/advogados'
import { Route as AuthenticatedCadastrosRouteImport } from './routes/_authenticated/cadastros'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDistribuicaoRouteImport } from './routes/_authenticated/distribuicao'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdvogadosRoute = AuthenticatedAdvogadosRouteImport.update({
  id: '/advogados',
  path: '/advogados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCadastrosRoute = AuthenticatedCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDistribuicaoRoute =
  AuthenticatedDistribuicaoRouteImport.update({
    id: '/distribuicao',
    path: '/distribuicao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advogados': typeof AuthenticatedAdvogadosRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/distribuicao': typeof AuthenticatedDistribuicaoRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advogados': typeof AuthenticatedAdvogadosRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/distribuicao': typeof AuthenticatedDistribuicaoRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/advogados': typeof AuthenticatedAdvogadosRoute
  '/_authenticated/cadastros': typeof AuthenticatedCadastrosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/distribuicao': typeof AuthenticatedDistribuicaoRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advogados'
    | '/cadastros'
    | '/dashboard'
    | '/distribuicao'
    | '/empresas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advogados'
    | '/cadastros'
    | '/dashboard'
    | '/distribuicao'
    | '/empresas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/advogados'
    | '/_authenticated/cadastros'
    | '/_authenticated/dashboard'
    | '/_authenticated/distribuicao'
    | '/_authenticated/empresas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/advogados': {
      id: '/_authenticated/advogados'
      path: '/advogados'
      fullPath: '/advogados'
      preLoaderRoute: typeof AuthenticatedAdvogadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros': {
      id: '/_authenticated/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof AuthenticatedCadastrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/distribuicao': {
      id: '/_authenticated/distribuicao'
      path: '/distribuicao'
      fullPath: '/distribuicao'
      preLoaderRoute: typeof AuthenticatedDistribuicaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdvogadosRoute: typeof AuthenticatedAdvogadosRoute
  AuthenticatedCadastrosRoute: typeof AuthenticatedCadastrosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDistribuicaoRoute: typeof AuthenticatedDistribuicaoRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdvogadosRoute: AuthenticatedAdvogadosRoute,
  AuthenticatedCadastrosRoute: AuthenticatedCadastrosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDistribuicaoRoute: AuthenticatedDistribuicaoRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
